using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Portfolio.Domain.Entities;

namespace Portfolio.Infrastructure.Data.Configurations
{
    public class WalletConfiguration : IEntityTypeConfiguration<Wallet>
    {
        public void Configure(EntityTypeBuilder<Wallet> builder)
        {
            // Configure the Id as the primary key
            builder.HasKey(w => w.Id);

            // Configure Id to be auto-generated by the database (optional, depending on your database setup)
            builder.Property(w => w.Id)
                   .ValueGeneratedOnAdd();

            // Configure Name as a required property with a maximum length
            builder.Property(w => w.Name)
                   .IsRequired()
                   .HasMaxLength(100);

            builder.HasMany(w => w.Holdings)
                   .WithOne()
                   .HasForeignKey("WalletId")
                   .OnDelete(DeleteBehavior.Cascade);
        }
    }
}
